"""Evaluate human song-emotion labels and catalogue recommendation quality.

Requires reports/human_validation/human_annotations.csv generated by
annotation_app.py. No labels are fabricated if the file is absent.
"""
from pathlib import Path
import json
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, balanced_accuracy_score, classification_report, confusion_matrix, f1_score

ROOT = Path(__file__).resolve().parents[1]
ANN = ROOT / "reports" / "human_validation" / "human_annotations.csv"
CAT = ROOT / "data" / "processed" / "labelled_catalogue.csv"
OUT = ROOT / "reports" / "human_validation"
EMOTIONS = ["sadness", "joy", "love", "anger", "fear", "surprise"]

if not ANN.exists():
    raise SystemExit("No human annotations found. Run tools/annotation_app.py first; no metrics are fabricated.")
ann = pd.read_csv(ANN)
required = {"annotator_id", "song_id", "emotion"}
missing = required - set(ann.columns)
if missing:
    raise SystemExit(f"Annotation file is missing columns: {sorted(missing)}")
ann["song_id"] = ann["song_id"].astype(str)
ann["annotator_id"] = ann["annotator_id"].astype(str)
ann = ann.drop_duplicates(["annotator_id", "song_id"], keep="last")
ann = ann[ann["emotion"].isin(EMOTIONS)].copy()
if ann.empty:
    raise SystemExit("No usable six-emotion annotations found; unclear-only rows cannot establish emotion metrics.")

cat = pd.read_csv(CAT)
cat["song_id"] = cat["id"].astype(str)

# Majority-vote reference label.
votes = ann.pivot_table(index="song_id", columns="emotion", values="annotator_id", aggfunc="count", fill_value=0).reindex(columns=EMOTIONS, fill_value=0)
votes["annotator_count"] = votes.sum(axis=1)
votes["final_emotion"] = votes[EMOTIONS].idxmax(axis=1)
votes["agreement"] = votes[EMOTIONS].max(axis=1) / votes["annotator_count"].replace(0, np.nan)
ref = votes.reset_index()
merged = ref.merge(cat, on="song_id", how="left", validate="one_to_one")
prob_cols = [f"emotion_prob_{e}" for e in EMOTIONS]
missing_prob = [c for c in prob_cols if c not in merged.columns]
if missing_prob:
    raise SystemExit(f"Catalogue is missing normalized emotion columns: {missing_prob}")
merged["predicted_emotion"] = merged[prob_cols].idxmax(axis=1).str.replace("emotion_prob_", "", regex=False)
valid = merged.dropna(subset=["predicted_emotion", "final_emotion"])

# Fleiss' kappa across songs with >=2 usable emotion ratings. This measures
# inter-annotator agreement rather than agreement with Moodify.
counts = votes[votes["annotator_count"] >= 2][EMOTIONS].to_numpy(dtype=float)
if len(counts):
    n = counts.sum(axis=1)
    p_i = (np.sum(counts * (counts - 1), axis=1) / (n * (n - 1)))
    p_bar = float(np.mean(p_i))
    p_j = counts.sum(axis=0) / counts.sum()
    p_e = float(np.sum(p_j ** 2))
    fleiss_kappa = (p_bar - p_e) / (1 - p_e) if p_e < 1 else 1.0
else:
    fleiss_kappa = None

summary = {
    "songs_with_human_labels": int(len(valid)),
    "total_annotation_rows": int(len(ann)),
    "annotators": sorted(ann["annotator_id"].unique().tolist()),
    "songs_with_at_least_3_emotion_annotations": int((votes["annotator_count"] >= 3).sum()),
    "catalogue_emotion_accuracy": float(accuracy_score(valid["final_emotion"], valid["predicted_emotion"])),
    "catalogue_emotion_balanced_accuracy": float(balanced_accuracy_score(valid["final_emotion"], valid["predicted_emotion"])),
    "catalogue_emotion_macro_f1": float(f1_score(valid["final_emotion"], valid["predicted_emotion"], labels=EMOTIONS, average="macro", zero_division=0)),
    "mean_majority_agreement": float(valid["agreement"].mean()),
    "fleiss_kappa": fleiss_kappa,
}
(OUT / "human_emotion_metrics.json").write_text(json.dumps(summary, indent=2))
pd.DataFrame(classification_report(valid["final_emotion"], valid["predicted_emotion"], labels=EMOTIONS, output_dict=True, zero_division=0)).T.to_csv(OUT / "human_emotion_classification_report.csv")
pd.DataFrame(confusion_matrix(valid["final_emotion"], valid["predicted_emotion"], labels=EMOTIONS), index=EMOTIONS, columns=EMOTIONS).to_csv(OUT / "human_emotion_confusion_matrix.csv")

# Recommendation evaluation on annotated songs only. This evaluates the
# emotion-conditioned catalogue ranking itself, without pretending that
# unannotated songs have human relevance labels.
ks = [5, 10]
rows = []
for emotion in EMOTIONS:
    prob = f"emotion_prob_{emotion}"
    pool = merged.copy()
    pool["relevance"] = (pool["final_emotion"] == emotion).astype(int)
    pool["rank_score"] = 0.90 * pd.to_numeric(pool[prob], errors="coerce").fillna(0) + 0.10 * (pd.to_numeric(pool["popularity"], errors="coerce").fillna(0).clip(0,100) / 100)
    pool = pool.sort_values(["rank_score", prob, "popularity"], ascending=False)
    for k in ks:
        top = pool.head(min(k, len(pool)))
        precision = float(top["relevance"].mean()) if len(top) else 0.0
        gains = top["relevance"].to_numpy(dtype=float)
        discounts = 1 / np.log2(np.arange(2, len(gains)+2))
        dcg = float(np.sum(gains * discounts))
        ideal_n = min(int(pool["relevance"].sum()), len(gains))
        idcg = float(np.sum(np.ones(ideal_n) * discounts[:ideal_n])) if ideal_n else 0.0
        ndcg = dcg / idcg if idcg else 0.0
        unique_artists = top["artist_text"].nunique() if "artist_text" in top else 0
        diversity = unique_artists / max(len(top), 1)
        rows.append({"emotion": emotion, "k": k, "precision_at_k": precision, "ndcg_at_k": ndcg, "artist_diversity": diversity})
pd.DataFrame(rows).to_csv(OUT / "recommendation_human_metrics.csv", index=False)
print(json.dumps(summary, indent=2))
print(f"Wrote human validation reports to {OUT}")
